// 초등학교 영단어
const elementaryWords = [
    { word: "apple", meaning: "사과" },
    { word: "book", meaning: "책" },
    { word: "cat", meaning: "고양이" },
    { word: "dog", meaning: "개" },
    { word: "egg", meaning: "달걀" },
    { word: "fish", meaning: "물고기" },
    { word: "girl", meaning: "소녀" },
    { word: "house", meaning: "집" },
    { word: "ice", meaning: "얼음" },
    { word: "jump", meaning: "뛰다" },
    { word: "king", meaning: "왕" },
    { word: "love", meaning: "사랑" },
    { word: "moon", meaning: "달" },
    { word: "nose", meaning: "코" },
    { word: "orange", meaning: "오렌지" },
    { word: "pen", meaning: "펜" },
    { word: "queen", meaning: "여왕" },
    { word: "red", meaning: "빨간색" },
    { word: "sun", meaning: "태양" },
    { word: "tree", meaning: "나무" },
    { word: "umbrella", meaning: "우산" },
    { word: "water", meaning: "물" },
    { word: "yellow", meaning: "노란색" },
    { word: "zoo", meaning: "동물원" },
    { word: "bird", meaning: "새" },
    { word: "car", meaning: "자동차" },
    { word: "door", meaning: "문" },
    { word: "eye", meaning: "눈" },
    { word: "friend", meaning: "친구" },
    { word: "green", meaning: "초록색" }
];

// 중학교 영단어
const middleWords = [
    { word: "beautiful", meaning: "아름다운" },
    { word: "challenge", meaning: "도전" },
    { word: "develop", meaning: "발전시키다" },
    { word: "education", meaning: "교육" },
    { word: "favorite", meaning: "좋아하는" },
    { word: "government", meaning: "정부" },
    { word: "hospital", meaning: "병원" },
    { word: "important", meaning: "중요한" },
    { word: "journey", meaning: "여행" },
    { word: "knowledge", meaning: "지식" },
    { word: "library", meaning: "도서관" },
    { word: "mountain", meaning: "산" },
    { word: "necessary", meaning: "필요한" },
    { word: "opportunity", meaning: "기회" },
    { word: "practice", meaning: "연습" },
    { word: "question", meaning: "질문" },
    { word: "remember", meaning: "기억하다" },
    { word: "science", meaning: "과학" },
    { word: "temperature", meaning: "온도" },
    { word: "understand", meaning: "이해하다" },
    { word: "village", meaning: "마을" },
    { word: "wonderful", meaning: "훌륭한" },
    { word: "exercise", meaning: "운동" },
    { word: "foreign", meaning: "외국의" },
    { word: "graduate", meaning: "졸업하다" },
    { word: "holiday", meaning: "휴일" },
    { word: "interest", meaning: "관심" },
    { word: "language", meaning: "언어" },
    { word: "medicine", meaning: "약" },
    { word: "nature", meaning: "자연" }
];

// 고등학교 영단어
const highWords = [
    { word: "accomplish", meaning: "성취하다" },
    { word: "beneficial", meaning: "유익한" },
    { word: "contribute", meaning: "기여하다" },
    { word: "distinguish", meaning: "구별하다" },
    { word: "environment", meaning: "환경" },
    { word: "fundamental", meaning: "기본적인" },
    { word: "guarantee", meaning: "보장하다" },
    { word: "hypothesis", meaning: "가설" },
    { word: "illustrate", meaning: "설명하다" },
    { word: "justify", meaning: "정당화하다" },
    { word: "knowledgeable", meaning: "박식한" },
    { word: "laboratory", meaning: "실험실" },
    { word: "magnificent", meaning: "웅장한" },
    { word: "nevertheless", meaning: "그럼에도 불구하고" },
    { word: "obstacle", meaning: "장애물" },
    { word: "phenomenon", meaning: "현상" },
    { word: "qualification", meaning: "자격" },
    { word: "recommendation", meaning: "추천" },
    { word: "significant", meaning: "중요한" },
    { word: "technique", meaning: "기법" },
    { word: "university", meaning: "대학교" },
    { word: "volunteer", meaning: "자원봉사자" },
    { word: "widespread", meaning: "널리 퍼진" },
    { word: "analyze", meaning: "분석하다" },
    { word: "characteristic", meaning: "특징" },
    { word: "demonstrate", meaning: "증명하다" },
    { word: "efficient", meaning: "효율적인" },
    { word: "foundation", meaning: "기초" },
    { word: "generation", meaning: "세대" },
    { word: "hesitate", meaning: "망설이다" }
];

// 레벨별 단어 데이터 매핑
const wordData = {
    elementary: elementaryWords,
    middle: middleWords,
    high: highWords
};

